### PR TITLE
Add new functionality and fix bugs

### PR DESCRIPTION
**Pull request by Alukardd**
###### here is example of my usage of this cookbook (part of role file):

``` ruby
"vim_config" => {
  "force_update" => true,
  "plugin_manager" => "pathogen",
  "bundles" => {
    "git" => [
      "git://github.com/tpope/vim-endwise.git"
    ]
  },
  "config_file_mode" => "template_from_attrs",
  "vimrc" => {
    "config" => {
      "system_wide" => [
        "syntax on",
        "set number"
      ],
      "user_specific" => {
        "root" => [
          'set statusline=%<%f%h%m%r%=format=%{&fileformat}\ file=%{&fileencoding}\ enc=%{&encoding}\ %b\ 0x%B\ %l,%c%V\ %P'
        ]
      }
    }
  }
}
```

Later I'll try to read config from data_bags and merge it with attributes from roles.

### CODE REVIEW

**Comment by promisedlandt** [comment]
Thank you very much for your work.
Unfortunately, I'm really busy at the moment, so I can't check everything out in depth yet.

A few quick notes:
- could you remove the copyright from `recipes/_config_template_from_attrs.rb`? I want to release this cookbook as a whole under one license (MIT)
- please use the same style as is used in other recipes: new hash colon notation, spaces in string interpolation, double quotes even when not needed
- In the vimrc template, why do you limit it to 3 levels of indentation, and why is Array not allowed on first level?

All in all, looks like good functionality!

**Comment by Alukardd** [comment]
only 3 levels limits because i didn't invent how implement it recursively...
First level is array itself.
yes, I can remove copyright, only this line?
why u use double quote? It's not good for everywhere.

**Comment by Alukardd** [comment]
This is example of usage 3 levels:

``` ruby
"user_specific" => {
          "root" => [
            "set iskeyword=@,48-57,_,192-255",
            "set langmap=ёйцукенгшщзхъфывапролджэячсмитьбю;`qwertyuiop[]asdfghjkl\\\\;'zxcvbnm\\\\,.,ЙЦУКЕHГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ;QWERTYUIOP{}ASDFGHJKL:\\\\\"ZXCVBNM<>",
            "",
            {
              "function! JavaScriptFold()" => [
                "setl foldmethod=syntax",
                "setl foldlevelstart=1",
                "syn region foldBraces start=/{/ end=/}/ transparent fold keepend extend",

                { "function! FoldText()" => "return substitute(getline(v:foldstart), '{.*', '{...}', '')" },
                "endfunction",
                "setl foldtext=FoldText()"
              ]
            },
            "endfunction"
          ]
        }
```

It's not look like nice, but work.

**Comment by promisedlandt** [comment]
Thank you for your patience, work has been very hard for me.

Can you please pull from my Alukardd-develop branch and check if that works for you with the vimrc from attribute?
I reworked the vimrc creation, but left all the cookbook stuff the same.

Please let me know if it doesn't work, so I can fix it.

**Comment by Alukardd** [comment]
Hi, I'll try to check your work the day after tomorrow.

**Comment by Alukardd** [comment]
I reviewed your code — it looks good and work fine. Good job!

But in my code still exists one problem: Mixlib::ShellOut executing at compilation time not in runtime, therefore if user for which I want to create ~/.vimrc file will be created only at this chef run, that config will not be created. I don't know how to execute it only in runtime, not in too early compilation time.

**Comment by promisedlandt** [comment]
Finally got around to it.  
Renamed the config option to simply "attributes" instead of "config_from_attrs", other than that it works as expected.

I was unable to fix the issue with creating config files for users that are created during the same run, and I don't think it's the responsibility of this cookbook to implement that.

If you can't wait for the second chef run, you need to manually notify the config creation on the user creation, but I'm not sure how do it since it's not an LWRP, sorry.

**Pull request merged**
